site_name: Phan Nguyen Ngoc Hien

nav:
    - Overview: index.md

    - Education: education.md

    - Experiences: experiences.md

    - Certificates: certificates.md

    - About Me: personal_info.md
    
theme: 
    name: readthedocs
    custom_dir: 'readthedocs_color'
    features:
        - search.highlight

use_directory_urls: false

plugins:
  - search:
        lang: en