site_name: Phan Nguyen Ngoc Hien

nav:
    - Overview: index.md

    - Education: education.md

    - Experiences: experiences.md

    - Certificates: certificates.md

    - Personal Information: personal_info.md
    
theme: 
    name: readthedocs
    custom_dir: 'readthedocs_color'


use_directory_urls: false